# runs tests for push-events, for pull requests and using cron schedule:
name: Run Robot Framework Tests
on:
  push:
    # runs tests for commits pushed to master
    branches:
      - master
    # do not run tests if file README.md changes
    paths-ignore:
      - 'README.md'
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
  pull_request:
    paths-ignore:
      - 'README.md'
  schedule:
    # run tests from Monday to Friday at 09:10 am
    - cron:  '0 09 10 * 1-5'
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        # checkout code from a repository
        - uses: actions/checkout@v2
        # create folder for test reports
        - name: Create folder for reports
          run: mkdir reports
        # run Robot Framework tests inside Docker container
        - name: Run Robot Framework Tests
          # container used here is ppodgorsek/robot-framework:latest
          # see container documentation for usage: https://hub.docker.com/r/ppodgorsek/robot-framework/dockerfile
          # it is required that GitHub repository contains folder "reports". Commit some file inside "reports" to create it
          # place tests in folder tests or change docker run command accordingly
          # configure -e ROBOT_OPTIONS according to yout tests, or remove it if no special configuration is needed
          run: |
            docker run \
              -e ROBOT_OPTIONS="--nostatusrc" \
              -e ROBOT_THREADS=4 \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/test:/opt/robotframework/tests:Z \
              -v ${PWD}/Resources:/opt/robotframework/Resources:Z \
              -v ${PWD}/PageObjects:/opt/robotframework/PageObjects:Z \
              -e BROWSER=chrome \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:3.8.0
        # upload test reports as a zip file, from above I removed -e ROBOT_THREADS=2 #ppodgorsek/robot-framework:3.7.0\
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
            path: ${{ github.workspace }}/reports
        # repository name is needed for posting test report in a next step
        - name: Get Repository Owner & Name
          run: |
            export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
            export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
            echo "REPOSITORY_OWNER=$OWNER" >> $GITHUB_ENV
            echo "REPOSITORY_NAME=$REPO" >> $GITHUB_ENV
         #Fix was done around security in the reporting part
         #when test are run for a commit, post results as a comment
         note: comment is not posted for tests triggered for pull requests, only for a main branch (master)
        #Reporting repository needs fixing and for the moment it will stay on SKIP
        - name: Send test report as comment to commit
          uses: joonvena/robotframework-reporter-action@v1.0
          if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
          env:
            GH_ACCESS_TOKEN: ${{ github.TOKEN }}
            REPO_OWNER: ${{ github.REPOSITORY_OwNER }}
            COMMIT_SHA: ${{ github.SHA }}
            REPOSITORY: ${{ env.REPOSITORY_NAME }}
            REPORT_PATH: ${{ github.workspace }}/reports

        - name: Notify Slack Success
          uses: drilonrecica/action-slack-notify@0.0.3
          if: success()
          env:
            SLACK_CHANNEL: robot_ci_results
            SLACK_COLOR: '#3278BD'
            SLACK_ICON: https://i.ytimg.com/vi/WIIm6eeqKM4/maxresdefault.jpg
            SLACK_MESSAGE: 'All done, updates from Mr.Robot:rocket::inshur::robot_face:'
            SLACK_TITLE: testresults
            SLACK_USERNAME: Mr Robot
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
